### ISSUE TITLE
Specified key was too long; max key length is 767 bytes: create unique index IX_9738C4E2 on Limsmuc_Conversation (conversationId);_ [Sanitized]

### ISSUE THREAD

**Issue by bill2004158** [marcelmika/lims#201]
create table Limsmuc_Conversation (
	cid LONG not null primary key,
	conversationId VARCHAR(256) null,
	conversationType INTEGER,
	updatedAt DATE null,
	syncIdSUC LONG
);

create unique index IX_9738C4E2 on Limsmuc_Conversation (conversationId);

it will happend if that error if charset is utf.

fix:
change conversationId  to VARCHAR(255)

**Comment by marcelmika** [comment]
fixed by setting the size of conversationId column to 255
